#+TITLE: Frequently Asked Questions

* FAQ                                                       :TOC_4_gh:noexport:
 - [[#common][Common]]
   - [[#我正在运行哪个版本的-spacemac][我正在运行哪个版本的 Spacemac？]]
   - [[#spacemacs-的官方发音是什么][Spacemacs 的官方发音是什么？]]
   - [[#你们为什么称之为发行版我看不到任何 spacemacs 可执行文件][你们为什么称之为“发行版”，我看不到任何“Spacemacs”可执行文件？]]
   - [[#为什么用-package-install-安装的软件包在-spacemacs-启动时自动删除][为什么用 =package-install= 安装的软件包在 Spacemacs 启动时自动删除？]]
   - [[#如何在安装-spacemacs-时修复软件包下载错误][如何在安装 Spacemacs 时修复软件包下载错误？]]
   - [[#如何修复启动时-symbols-value-as-variable-is-void-错误][如何修复启动时 =Symbol's value as variable is void= 错误？]]
   - [[#如何修复启动时-wrong-type-argument-arrayp-nil-错误][如何修复启动时 =(wrong-type-argument arrayp nil)= 错误？]]
   - [[#spacemacs-标志是丑陋的我该怎么办][Spacemacs 标志是丑陋的，我该怎么办？]]
   - [[#powerline-分隔符是丑陋的我该如何解决][powerline 分隔符是丑陋的，我该如何解决？]]
   - [[#powerline-分隔符没有抗锯齿我该怎么办][powerline 分隔符没有抗锯齿，我该怎么办？]]
   - [[#为什么没有执行-after-init-hook][为什么没有执行 after-init-hook？]]
    - [[#spacemacs-base-和-spacemacs-发行版有什么区别][=spacemacs-base= 和 =spacemacs= 发行版有什么区别？]]
   - [[#我应该把我的设置放在-user-init-还是-user-config-][我应该把我的设置放在 =user-init= 还是 =user-config= ？]]
   - [[#为什么我的某些-org-相关设置会导致问题][为什么我的某些 =org= 相关设置会导致问题？]]
   - [[#为什么-spacemacs-在启动时挂起][为什么 Spacemacs 在启动时挂起？]]
   - [[#为什么-helm-m-x-spc-spc-不接受前缀参数][为什么 =helm-M-x= (~SPC SPC~) 不接受前缀参数？]]
   - [[#为什么我的颜色主题在终端模式下不能正确渲染][为什么我的颜色主题在终端模式下不能正确渲染？]]
   - [[#快速键入-fd-带我离开-插入状态-到底是怎么回事][快速键入 =fd= 带我离开 =插入状态= 。到底是怎么回事？]]
   - [[#为什么我得到以开头的文件][为什么我得到以.#开头的文件？]]
   - [[#为什么我会在-ansi-term-期内得到-4m-的字符][为什么我会在 ansi-term 期内得到 '4m' 的字符？]]
   - [[#为什么我的字体设置不被尊重][为什么我的字体设置不被尊重？]]
   - [[#为什么我在启动时收到有关环境变量的消息][为什么我在启动时收到有关环境变量的消息？]]
 - [[#how-do-i][How do I:]]
   - [[#安装不是由层提供的包][安装不是由层提供的包？]]
   - [[#完全禁用包][完全禁用包？]]
   - [[#仅针对特定主模式禁用软件包][仅针对特定主模式禁用软件包？]]
   - [[#对特定主模式禁用-company][对特定主模式禁用 company？]]
   - [[#更改特殊的缓冲区规则][更改特殊的缓冲区规则？]]
   - [[#通过-visual-lines-启用导航][通过 visual lines 启用导航？]]
   - [[#禁止一种模式的-evilification][禁止一种模式的 evilification？]]
   - [[#在单词运动-motions-中加上下划线][在单词运动 motions 中加上下划线？]]
   - [[#设置-path][设置 =$PATH=?]]
   - [[#更改或定义前缀键的别名][更改或定义前缀键的别名？]]
   - [[#将句子分隔符还原到两个空格][将句子分隔符还原到两个空格？]]
   - [[#防止可视化选择覆盖我的系统剪贴板][防止可视化选择覆盖我的系统剪贴板？]]
   - [[#拼写检查支持卷曲引号或任何其他字符][拼写检查支持卷曲引号（或任何其他字符）？]]
   - [[#使用-spacemacs-作为-git-提交的-editor-][使用 Spacemacs 作为 git 提交的 =$EDITOR= ？]]
   - [[#尝试-spacemacs-而不修改我现有的-emacs-配置][尝试 Spacemacs 而不修改我现有的 Emacs 配置？]]
   - [[#在-x11-终端上使用鼠标进行复制粘贴][在 X11 终端上使用鼠标进行复制/粘贴？]]
   - [[#使用-helm-ag-仅搜索某种类型的文件][使用 =helm-ag= 仅搜索某种类型的文件？]]
   - [[#修改-spacemacs-文档外观 space-doc-mode][修改 spacemacs 文档外观（space-doc-mode）]]
   - [[#重新映射粘贴键以便能够多次粘贴复制的文本][重新映射粘贴键，以便能够多次粘贴复制的文本]]
 - [[#windows][Windows]]
   - [[#为什么字体在-windows-上看起来很糟糕][为什么字体在 Windows 上看起来很糟糕？]]
   - [[#为什么启动缓冲区中没有-spacemacs-标志][为什么启动缓冲区中没有 Spacemacs 标志？]]
   - [[#为什么所有软件包不可用][为什么所有软件包不可用？]]
   - [[#在-putty-中使用-spacemacs-时 powerline-未正确显示][在 =PuTTY= 中使用 Spacemacs 时，powerline 未正确显示]]

* Common
** 我正在运行哪个版本的 Spacemac？
版本显示在加载屏幕的右上角。您也可以键入 ~SPC f e v~ 。

** Spacemacs 的官方发音是什么？
正如它写的那样，那就是先 _space_ 然后是 _macs_ 。

** 你们为什么称之为“发行版”，我看不到任何“Spacemacs”可执行文件？
虽然我们可以做到这一点，但是我们不会将 Emacs 与 Spacemacs 打包在一起。我们允许用户选择他们想要的与其操作系统一起使用的编译的 Emacs，这更加灵活而且可以省下大量的问题。Spacemacs 不仅仅是 Emacs 的配置，它配备了高级功能，概念和工具。大概地将其视为 Linux 发行版，我们会要求用户首先安装内核，然后以某种方式获取实际的代码以获取分发。请注意，一些 Linux 发行版可能会开始为 Spacemacs 创建软件包，它们是非官方软件包，我们永远不会使用 Spacemacs 来打包 Emacs。

** 为什么用 =package-install= 安装的软件包在 Spacemacs 启动时自动删除？
默认情况下，Spacemacs 将仅保留您使用的包（即，属于显式列在变量 =dotspacemacs-configuration-layers= 中的图层的包）。

要安装不属于任何 Spacemacs 层的软件包，您可以：

- 使用变量 =dotspacemacs-additional-packages= 。
- 或者创建一个配置层，并将此层添加到 =dotspacemacs-configuration-layer= 
- 或者将 =dotspacemacs-install-packages= 变量设置为 =used-but-keep-unused= ，这样可以防止 Spacemacs 删除手动安装的软件包。

要创建新的配置层，请参阅 [[file:QUICK_START.org][快速入门指南]] 了解更多信息。

** 如何在安装 Spacemacs 时修复软件包下载错误？
从 0.105.0 版本开始，默认使用 HTTPS 协议来下载软件包。如果您的环境不允许 HTTPS 到达 ELPA 存储库，那么您可以使用 =--insecure= 参数启动 Emacs 强制使用 HTTP 非安全协议。您可以在点文件中将变量 =dotspacemacs-elpa-https= 设置为 =nil= ，以消除使用 =--insecure= 参数启动 Emacs 的需要。

** 如何修复启动时 =Symbol's value as variable is void= 错误？
如果 Emacs 报告错误符号已关闭或 =-= 作为变量未绑定，可能是因为您正在使用 HTTPS 下载软件包，但你不应该这样做。尝试删除您的软件包（ =.emacs.d/elpa= 文件夹），并重新启动没有 HTTPS 的 Emacs 来再次下载软件包。 有两种方法：

- 使用 =--insecure= 命令行参数运行 Emacs： =emacs --insecure= 。下次更新您的包时，您将不得不再次执行此操作。
- 在 dotfile 中将变量 =dotspacemacs-elpa-https= 设置为 =nil= 。这与 =--insecure= 具有相同的效果，但是是持久的。

** 如何修复启动时 =(wrong-type-argument arrayp nil)= 错误？
这很可能是由于损坏的软件包归档引起的。尝试删除您的 =~/.emacs.d/elpa/archives/= 文件夹并重启 Emacs。

** Spacemacs 标志是丑陋的，我该怎么办？
安装 Spacemacs 支持的默认字体或选择固定宽度的字体。更多信息在 [[file:DOCUMENTATION.org][文档]] 中的字体部分。

** powerline 分隔符是丑陋的，我该如何解决？
使用变量 =dotspacemacs-default-font= 的 =:powerline-scale= 属性。有关更多详细信息，请参阅 [[file:DOCUMENTATION.org][文档]] 的字体部分。

** powerline 分隔符没有抗锯齿，我该怎么办？
Emacs powerline 使用 XMP 图像在图形环境中绘制分隔符。如果使用 =utf8= 分隔符，则可以使用抗锯齿功能。请注意，在终端中默认使用 =utf8= 分隔符。请参阅 [[file:DOCUMENTATION.org][文档]] 字体部分的 powerline 部分。

** 为什么没有执行 after-init-hook？
不要使用 =emacs -q -l init.el= 命令启动 Spacemacs。该命令在对过去的 =-l init.el= 文件进​​行评估之前，将在 =after-init-hook= 中运行挂钩的函数。

**  =spacemacs-base= 和 =spacemacs= 发行版有什么区别？
发行版的概念在 0.104.x 被引入。您现在可以在两个发行版之间选择 =spacemacs-base= 或 =spacemacs= 。 =spacemacs-base= 只包含一小部分包; 而 =spacemacs= 是完整的 Spacemacs 体验。

使用 =dotspacemacs-distribution= 变量设置发行版。默认是 =spacemacs= 。有关包含的内容的更多信息，请查看 =+distributions= 文件夹中的 =layers/= 目录中相应文件夹中的 =packages.el= 文件。

** 我应该把我的设置放在 =user-init= 还是 =user-config= ？
必须在 =user-init= 中设置 层配置代码会 *读取* 和 *操作* 的任何变量，并且必须在 =user-config= 中设置 Spacemacs 显式设置但是你想 *覆盖* 的任何变量。

任何不仅仅是设置一个变量的东西应该在 =user-config= 中。

** 为什么我的某些 =org= 相关设置会导致问题？
自从版本 0.104，spacemacs 使用来自 ELPA 仓库的 =org= 版本而不是 emacs 附带的版本。然后，在 =dotspacemacs/user-config= 之前不应该加载任何 =org= 相关的代码，否则两个版本都将被加载并且会发生冲突。

由于自动加载，调用 =org= 函数将触发加载与 emacs 附带的 =org= ，这将引发冲突。避免冲突的一种方法是将您的 org 配置代码包含在一个 =with-eval-after-load= 块中，如下所示：

#+BEGIN_SRC emacs-lisp
(with-eval-after-load 'org
  ;; here goes your Org config :)
  ;; ....
  )
#+END_SRC

** 为什么 Spacemacs 在启动时挂起？
这可能与 Helm 使用 Tramp 有关，它试图在启动时找出一些 SSH / DNS 设置。根本原因可能是您的 ISP 将不存在的地址重定向到自己的服务器。

尝试在 =.spacemacs= 配置中的 =user-init= 函数中使用这些设置：

#+BEGIN_SRC emacs-lisp
(setq tramp-ssh-controlmaster-options
      "-o ControlMaster=auto -o ControlPath='tramp.%%C' -o ControlPersist=no")
#+END_SRC


有关详细信息，请参阅 [[https://github.com/syl20bnr/spacemacs/issues/3422#issuecomment-148919047][issue #3422]] 和 [[https://github.com/emacs-helm/helm/issues/1000#issuecomment-119487649][helm issue #1000]] 。如果由于任何原因，此代码不工作，您可以尝试将这些设置直接放在 =~/.ssh/config= 中：

#+BEGIN_SRC ssh
Host *
ControlMaster auto
ControlPath ~/.ssh/master -%r@%h:%p
ControlPersist = no
#+END_SRC

** 为什么 =helm-M-x= (~SPC SPC~) 不接受前缀参数？
如果您尝试使用前缀参数（如 ~SPC u SPC SPC~ ）运行 =helm-M-x= ，则会失败并显示此消息：

#+BEGIN_VERSE
Error: Specifying a prefix arg before calling helm-M-x
#+END_VERSE

相反，首先调用 =helm-M-x= ，选择要运行的命令，然后按 ~C-u~ 键，然后按 ~RETURN~ 。例如： ~SPC SPC org-reload C-u RET~

** 为什么我的颜色主题在终端模式下不能正确渲染？
在 Emacs 的终端版本中，颜色主题将不会正确呈现，因为颜色由终端而不是由 emacs 呈现。您可能需要更改终端调色板。在 [[https://github.com/sellout/emacs-color-theme-solarized#important-note-for-terminal-users][emacs-color-theme-solarized webpage]] 网页上可以找到更多的说明。

** 快速键入 =fd= 带我离开 =插入状态= 。到底是怎么回事？
这是 Spacemacs 的一个功能，使您可以轻松地从许多情况中退出，例如从 =插入状态= 转移到 =普通状态= 。

使用的字符序列可以定制。有关详细信息，请参阅 [[http://spacemacs.org/doc/DOCUMENTATION.html#escaping][文档]] 。

如果不喜欢此功能，可以通过在 init 文件中的 =dotspacemacs-excluded-packages= 中添加 =evil-escape= 来停用它。

** 为什么我得到以.#开头的文件？
这些是由 Emacs 创建的锁文件，以防止由两个不同程序同时编辑同一文件时发生的编辑冲突。要禁用此行为：

#+BEGIN_SRC emacs-lisp
(setq create-lockfiles nil)
#+END_SRC

** 为什么我会在 ansi-term 期内得到 '4m' 的字符？
Ansi-term 只有 xterm256 支持的功能子集。您的 shell（例如 fish shell）可能会忽略 =$TERMINFO= 信息，并要求您自己设置 =~/.terminfo= 。

#+BEGIN_SRC fish
tic -o ~/.terminfo $TERMINFO/e/eterm-color.ti
#+END_SRC

请注意， =eterm-color.ti= 可能位于不同的位置，以查找它的确切位置，您可以尝试使用 =locate= ：

#+BEGIN_SRC fish
locate eterm-color.ti
#+END_SRC

** 为什么我的字体设置不被尊重？
 =dotspacemacs-default-font= 的设置（如 size，weight 等）只有在系统上存在字体名称时才会应用。检查以确保是这种情况。如果 Spacemacs 找不到字体，则在 =*Messages*= 缓冲区中应该会出现警告。

** 为什么我在启动时收到有关环境变量的消息？
当 Emacs 启动时，Spacemacs 使用 =exec-path-from-shell= 包来设置可执行路径。这是通过启动 shell 并从其读取变量值（如 =PATH= 和 =MANPATH= ）完成的。如果你的 shell 配置设置这些变量的值不一致，这可能是有问题的。建议将这些变量设置为无条件提供的 shell 配置文件，例如 =.profile= ， =.bash_profile= 或 =.zshenv= ，而不是仅用于交互式 shell 的文件，例如 =.bashrc= 或 =.zshrc= 。如果您愿意忽略此建议，您可以禁用警告，例如来自 =dotspacemacs/user-init= :

#+BEGIN_SRC emacs-lisp
  (setq exec-path-from-shell-check-startup-files nil)
#+END_SRC

如果您希望自己设置 =exec-path= ，您还可以通过将 =exec-path-from-shell= 添加到列表 =dotspacemacs-excluded-packages= 中来完全禁用此功能。

* How do I:
:PROPERTIES:
:CUSTOM_ID: how-do-i
:END:
** 安装不是由层提供的包？
Spacemacs 在 =.spacemacs= 中的 =dotspacemacs/layers= 函数中提供一个名为 =dotspacemacs-additional-packages= 的变量。只需将包名称添加到列表中，当您使用 ~SPC f e R~ 重新加载配置时，或在下一次 Spacemacs 启动时，它将被安装。

** 完全禁用包？
要完全禁用一个包并有效地卸载它，即使它是您使用的层的一部分，请在 dotfile 中查找变量 =dotspacemacs-excluded-packages= 并将其包名称添加到其中：

#+BEGIN_SRC emacs-lisp
(setq-default dotspacemacs-excluded-packages '(package1 package2 ...))
#+END_SRC

** 仅针对特定主模式禁用软件包？
这是通过删除由 Spacemacs 添加的钩子来完成的。例如，要删除 python 缓冲区中的 =flycheck= 支持，请在 dotfile 中查找函数 =dotspacemacs/user-config= ，并添加以下代码：

#+BEGIN_SRC emacs-lisp
(remove-hook 'python-mode-hook 'flycheck-mode)
#+END_SRC

*提示* 为了知道当前缓冲区主模式的名称： ~SPC h d v major-mode RET~

** 对特定主模式禁用 company？
如果您计划配置 =auto-complete= ，则可以方便地禁用给定模式的 =company= 。一个简单的方法是在你的 dotfile 的函数 =dotspacemacs/user-config= 中使用宏 =spacemacs|disable-company= 。以下代码段为 =python-mode= 禁用 company：

#+BEGIN_SRC emacs-lisp
(spacemacs|disable-company python-mode)
#+END_SRC

** 更改特殊的缓冲区规则？
   :PROPERTIES:
   :CUSTOM_ID: change-special-buffer-rules
   :END:
为了改变 spacemacs 将缓冲区标记为无用的方式，您可以自定义 =spacemacs-useless-buffers-regexp= ，它将与正则表达式匹配的缓冲区标记为无用。变量 =spacemacs-useful-buffers-regexp= 将与正则表达式匹配的缓冲区标记为有用的缓冲区。两者都可以相同的方式进行定制。

例子：
#+BEGIN_SRC emacs-lisp
;; Only mark helm buffers as useless
(setq spacemacs-useless-buffers-regexp '("\\*helm\.\+\\*"))

;; Marking the *Messages* buffer as useful
(push "\\*Messages\\*" spacemacs-useful-buffers-regexp)
#+END_SRC

** 通过 visual lines 启用导航？
将以下代码片段添加到您的 =dotspacemacs/user-config= 函数中：

#+BEGIN_SRC emacs-lisp
;; Make evil-mode up/down operate in screen lines instead of logical lines
(define-key evil-motion-state-map "j" 'evil-next-visual-line)
(define-key evil-motion-state-map "k" 'evil-previous-visual-line)
;; Also in visual mode
(define-key evil-visual-state-map "j" 'evil-next-visual-line)
(define-key evil-visual-state-map "k" 'evil-previous-visual-line)
#+END_SRC

** 禁止一种模式的 evilification？
您可以通过使用 =evil-set-initial-state= 来确保在 emacs 状态下打开模式。

#+BEGIN_SRC emacs-lisp
(evil-set-initial-state 'magit-status-mode 'emacs)
#+END_SRC

您也可以使用缓冲区名称正则表达式来执行此操作。例如，对于 magit，它有许多不同的主模式，你用以下代码可以获取他们：

#+BEGIN_SRC emacs-lisp
(push '("*magit" . emacs) evil-buffer-regexps)
#+END_SRC

这应该使所有原始的 magit 绑定在所讨论的主模式中工作。要在这种情况下启用前缀键，您可能必须在模式的 map 中定义绑定，例如对于 =magit-status-mode= ：

#+BEGIN_SRC emacs-lisp
(with-eval-after-load 'magit
  (define-key magit-status-mode-map
    (kbd dotspacemacs-leader-key) spacemacs-default-map))
#+END_SRC

** 在单词运动 motions 中加上下划线？
您可以修改相关模式的语法表。为此，您可以将其包含在您的 =dotspacemacs/user-config= 中：

#+BEGIN_SRC emacs-lisp
;; For python
(add-hook 'python-mode-hook #'(lambda () (modify-syntax-entry ?_ "w")))
;; For ruby
(add-hook 'ruby-mode-hook #'(lambda () (modify-syntax-entry ?_ "w")))
;; For Javascript
(add-hook 'js2-mode-hook #'(lambda () (modify-syntax-entry ?_ "w")))
#+END_SRC

** 设置 =$PATH=?
某些层需要您的 =$PATH= 上可用的某些工具。这意味着您的 =$PATH= 必须包含这些工具的安装路径。例如，如果您已经在 =~/.local/bin= 中安装了一些工具，并希望它们在 Spacemacs 中可用，则需要在 =$PATH= 中添加 =~/.local/bin= 。

=bash=, =zsh=, =sh= 和其他类似 shell 的用户应该添加以下行到 =.bashrc=, =.zshrc=, =.profile= 或你的 shell 的等效项）。请注意， =export= 部分非常重要。

#+BEGIN_SRC sh
export PATH=~/.local/bin:$PATH
#+END_SRC

 =fish= 用户应该在他们的 =config.fish= 文件中添加以下行（应该在 =$XDG_CONFIG_HOME= 或其默认值－－ =~/.config/fish= ）。注意 =-x= 部分非常重要。

#+BEGIN_SRC fish
set -x PATH ~/.local/bin $PATH
#+END_SRC

其他 shell 的用户应该参考有关如何设置 =$PATH= 变量（导出到环境）的文档。

所以现在， =~/.local/bin= 应该在 =$PATH= 中可用。您可以通过调用 =echo $PATH= 来验证这一点。但是您也应该验证 =$PATH= 是否在您的环境中正确设置。要做到这一点，请在您的终端中输入以下命令。

#+BEGIN_SRC sh
env | grep "PATH"
#+END_SRC

这是 Emacs 将使用的值。 所以它必须包含 =~/.local/bin= 。

之后，您可以运行 Spacemacs，并通过运行 =M-: (getenv "PATH")= 来正确获取 =$PATH= 的值。

请注意，在 =$PATH= 中具有 =~/.local/bin= 也意味着可以从 =~/.local/bin= 运行终端和调用工具，而不指定其完整路径。在某些情况下，您可能希望避免修改 =$PATH= 。在这种情况下，您可以选择在 =.spacemacs= 文件的 =dotspacemacs/user-config= 函数中更新 =exec-path= 的值。

#+BEGIN_SRC emacs-lisp
(add-to-list 'exec-path "~/.local/bin/")
#+END_SRC

** 更改或定义前缀键的别名？
可以通过将键盘映射绑定到另一个序列来更改前缀键。例如，如果要使用 ~SPC d~ （用破折号使用）来替换 ~SPC S~ （拼写）以使前者更容易到达，则可以使用：

#+BEGIN_SRC emacs-lisp
(defun dear-leader/swap-keys (key1 key2)
  (let ((map1 (lookup-key spacemacs-default-map key1))
        (map2 (lookup-key spacemacs-default-map key2)))
    (spacemacs/set-leader-keys key1 map2 key2 map1)))
(dear-leader/swap-keys "S" "d")
#+END_SRC

如果要定义自己的别名，例如使用 ~SPC é~ （因为它是键盘布局上的一个未使用的键）用于访问 ~SPC w~ （窗口管理），则可以使用以下命令：

#+BEGIN_SRC emacs-lisp
(defun dear-leader/alias-of (key1 key2)
  (let ((map (lookup-key spacemacs-default-map key2)))
    (spacemacs/set-leader-keys key1 map)))
(dear-leader/alias-of "é" "w")
#+END_SRC

** 将句子分隔符还原到两个空格？
要将句子分隔符恢复为两个空格，请将以下代码添加到 =.spacemacs= 的 =dotspacemacs/user-init= 函数中：

#+BEGIN_SRC emacs-lisp
(setq sentence-end-double-space t)
#+END_SRC

** 防止可视化选择覆盖我的系统剪贴板？
在某些操作系统上，只有一个剪贴板用于 *复制* 和 *选择* 的文本。这样做的结果是，可视化 *选择* （通常应保存到 /PRIMARY/ 剪贴板）会覆盖 /SYSTEM/ 剪贴板，这里通常会有 *复制* 的文本。可以通过将以下代码添加到 =.spacemacs= 的 =dotspacemacs/user-config= 来进行更正：

#+BEGIN_SRC emacs-lisp
(fset 'evil-visual-update-x-selection 'ignore)
#+END_SRC

** 拼写检查支持卷曲引号（或任何其他字符）？
要使拼写检查支持卷曲引号（或任何其他字符），您需要通过在 =.spacemacs= 的 =dotspacemacs/user-config= 中添加以下代码来为 =ispell-local-dictionary-alist= 添加新条目：

#+BEGIN_SRC emacs-lisp
(add-to-list 'ispell-local-dictionary-alist
  (quote ("my_english" "[[:alpha:]]" "[^[:alpha:]]" "['’]" t ("-d" "en_US") nil utf-8)))
#+END_SRC

然后，您可以在第四个参数中添加所需的任何正则表达式（即在 =['’]= 中添加一个符号）以使其得到支持。有关可能性的更多详细信息，请参阅 =ispell-dictionary-alist= 的帮助。

您最终必须将 =my_english= 设置为您的 =ispell-local-dictionary= ，以便使用支持您新添加的字符的字典。

** 使用 Spacemacs 作为 git 提交的 =$EDITOR= ？
Spacemacs 可以用作编辑 git 提交消息的 =$EDITOR= （或 =$GIT_EDITOR= ）。要启用此功能，您必须将以下行添加到您的 =dotspacemacs/user-config= 中：

#+BEGIN_SRC emacs-lisp
(global-git-commit-mode t)
#+END_SRC

** 尝试 Spacemacs 而不修改我现有的 Emacs 配置？
Emacs 使用任何目录作为启动的目录的能力允许我们尝试使用 Spacemacs（或任何其他我们想要的 Emacs 配置），而无需经历备份 =~/.emacs.d= 目录的麻烦，然后克隆新配置。这可以通过以下步骤轻松实现：

#+BEGIN_SRC sh
mkdir ~/spacemacs
git clone git@github.com:syl20bnr/spacemacs.git ~/spacemacs/.emacs.d
HOME=~/spacemacs emacs
#+END_SRC

如果你在 Fish shell 上，你需要把最后一个命令修改成： =env HOME=$HOME/spacemacs emacs=

** 在 X11 终端上使用鼠标进行复制/粘贴？
可以在 X11 终端中禁用鼠标支持，以便使用鼠标进行复制/粘贴。您需要将此行添加到您的 =dotspacemacs/user-config= ：

#+begin_src emacs-lisp
(xterm-mouse-mode -1)
#+end_src

** 使用 =helm-ag= 仅搜索某种类型的文件？
可以将 =helm-ag= 的范围限制为仅在某些指定的文件类型中搜索表达式。有两种方式可以做到這些，通过在搜索输入中附加一些表达式：

- 通过使用有 =-G= 的正则表达式，例如 =-G\.el$= 将查找以 =.el= 作为 emacs-lisp 文件结尾的所有文件。

- 通过使用 =--python= 这样应该是自我解释的标志。从终端可以访问可用标志的列表：

  #+begin_src shell
  ag --list-file-types
  #+end_src

这是可能的，因为 =helm-ag= 将搜索输入视为 =ag= 程序的命令行参数。

** 修改 spacemacs 文档外观（space-doc-mode）
您可以通过 =space-doc-mode= 修改应用的视觉增强功能列表：

#+BEGIN_SRC emacs-lisp
(setq spacemacs-space-doc-modificators
      '(center-buffer-mode
        org-indent-mode
        view-mode
        hide-line-numbers
        alternative-emphasis
        alternative-tags-look
        link-protocol
        org-block-line-face-remap
        org-kbd-face-remap
        resize-inline-images))
#+END_SRC

默认只有 =center-buffer-mode= 被禁用。 =space-doc-mode= 和 =center-buffer-mode= 都可以通过 "Easy Customization Interface" （“轻松定制界面”）进行定制。

** 重新映射粘贴键，以便能够多次粘贴复制的文本
在 vim 和 evil 中，在文本上粘贴会导致它被复制，因此使得不可能多次粘贴相同的文本。

要解决此问题，请将以下代码片段添加到 ~user-config~ 中：

#+BEGIN_SRC emacs-lisp
(defun evil-paste-after-from-0 ()
  (interactive)
  (let ((evil-this-register ?0))
    (call-interactively 'evil-paste-after)))

(define-key evil-visual-state-map "p" 'evil-paste-after-from-0)
#+END_SRC

* Windows
** 为什么字体在 Windows 上看起来很糟糕？
您可以在 Windows 上安装 [[https://code.google.com/archive/p/gdipp/][GDIPP]] （最简单）或 [[https://code.google.com/p/mactype/][MacType]] （更完整），以获得非常漂亮的字体。也建议在 Windows 上禁用平滑滚动。

** 为什么启动缓冲区中没有 Spacemacs 标志？
需要支持图像显示的 emacs 的 GUI 编译版本。你可以按照 [[http://stackoverflow.com/questions/2650041/emacs-under-windows-and-png-files][这里]] 的说明。或者，您可以下载包含图像支持的 emacs 二进制文件，比如 [[http://emacsbinw64.sourceforge.net/][这个]]。

** 为什么所有软件包不可用？
通过执行 =M-:= ，检查您的 Emacs 是否具有 HTTPS 功能，然后：

#+BEGIN_SRC emacs-lisp
  (gnutls-available-p)
#+END_SRC

如果这返回 =nil= ，则需要将 GnuTLS DLL 文件安装在与 Emacs 相同的目录中。看 [[https://www.gnu.org/software/emacs/manual/html_mono/emacs-gnutls.html#Help-For-Users][这里]] 的说明。

** 在 =PuTTY= 中使用 Spacemacs 时，powerline 未正确显示
你可以按照这个 [[http://mschulte.nl/posts/using-powerline-in-PuTTY.html][解释]] ，它说明如何纠正这个。
